# This is a Docker Compose file for an e-commerce microservices project.
# It defines services for user and product management, each with its own database.
services:
  user-service:
    build: ./user-service
    volumes:
      - ./user-service:/code
    ports:
      - "8000:8000"
    env_file:
      - ./user-service/.env
    depends_on:
      - user-db

  user-db:
    image: postgres:15
    env_file:
      - ./user-service/.env
    volumes:
      - user-db-data:/var/lib/postgresql/data

  product-service:
    build: ./product-service
    volumes:
      - ./product-service:/code
    ports:
      - "8001:8000"
    env_file:
      - ./product-service/.env
    depends_on:
      - product-db

  product-db:
    image: postgres:15
    env_file:
      - ./product-service/.env
    volumes:
      - product-db-data:/var/lib/postgresql/data

  order-service:
    build: ./order-service
    volumes:
      - ./order-service:/code
    ports:
      - "8002:8000"
    env_file:
      - ./order-service/.env
    depends_on:
      - order-db

  order-db:
    image: postgres:15
    env_file:
      - ./order-service/.env
    volumes:
      - order-db-data:/var/lib/postgresql/data

volumes:
  user-db-data:
  product-db-data:
  order-db-data:
