# This is a Docker Compose file for the e-commerce microservices.
# It defines services for user and product management, each with its own database.
services:
  user-service:
    build: ./user-service
    command: python manage.py runserver 0.0.0.0:8000
    container_name: user-service
    networks:
      - traefik
    volumes:
      - ./user-service:/code
    ports:
      - "8000:8000"
    env_file:
      - ./user-service/.env
    depends_on:
      - user-db

  user-db:
    image: postgres:15
    networks:         
      - traefik
    env_file:
      - ./user-service/.env
    volumes:
      - user-db-data:/var/lib/postgresql/data

  product-service:
    build: ./product-service
    command: python manage.py runserver 0.0.0.0:8000
    container_name: product-service
    networks:
      - traefik
    volumes:
      - ./product-service:/code
    ports:
      - "8001:8000"
    env_file:
      - ./product-service/.env
    depends_on:
      - product-db

  product-db:
    image: postgres:15
    networks:         
      - traefik
    env_file:
      - ./product-service/.env
    volumes:
      - product-db-data:/var/lib/postgresql/data

  order-service:
    build: ./order-service
    command: python manage.py runserver 0.0.0.0:8000
    container_name: order-service
    networks:
      - traefik
    volumes:
      - ./order-service:/code
    ports:
      - "8002:8000"
    env_file:
      - ./order-service/.env
    depends_on:
      - order-db

  order-db:
    image: postgres:15
    networks:         
      - traefik
    env_file:
      - ./order-service/.env
    volumes:
      - order-db-data:/var/lib/postgresql/data

  payment-service:
    build: ./payment-service
    command: python manage.py runserver 0.0.0.0:8000
    container_name: payment-service
    networks:
      - traefik
    volumes:
      - ./payment-service:/code
    ports:
      - "8003:8000"
    env_file:
      - ./payment-service/.env
    depends_on:
      - payment-db

  payment-db:
    image: postgres:15
    networks:         
      - traefik
    env_file:
      - ./payment-service/.env
    volumes:
      - payment-db-data:/var/lib/postgresql/data


networks:
  traefik:
    external: true

volumes:
  user-db-data:
  product-db-data:
  order-db-data:
  payment-db-data: